# -*- coding: utf-8 -*-
"""581_Final_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0SGmx1riiUpahSmohz7lhD169d87pUO
"""

import cv2
from google.colab.patches import cv2_imshow

"""Define a function that will take in an image, and return a processed version of the image that will allow python to properly detect the necessary contours (you can tweak the values to further meet your needs):"""

def preprocess(img):
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_blur = cv2.GaussianBlur(img_gray, (5, 5), 1)
    img_canny = cv2.Canny(img_blur, 50, 50)
    return img_canny
    # return img_blur

"""Now, let's see how we can define a function that will retrieve the ROI of the image. First, define it so that a processed image array and a pad amount (optional) can be passed in as parameters:"""

def get_region_of_interest(img, pad=3, num_diagrams=10):
    # three parameters to findContours:
      # 1.) Image
      # 2.) Contour retrieval mode
      # 3.) Contour approximation method
       
    contours, hierarchy = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    # contours, hierarchy = cv2.findContours(img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    # cv2.drawContours(img, contours, -1, (0,255,0), 3)

    max_area = 1 # originally 0
    dictionary = {}
    
    for cnt in contours:
        peri = cv2.arcLength(cnt, True)
        approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
        x, y, w, h = cv2.boundingRect(approx)
        rect_area = w * h
        # for key in dictionary:
        #   if rect_area > key:
        #     dictionary[]
        #   print(key, '->', a_dict[key])
        dictionary[rect_area] = (x, y, w, h)

        # if rect_area > max_area:
        #     max_area = rect_area
        #     dim = x, y, w, h
    
    keyset = set()
    to_return = []
    for __ in range(num_diagrams):
      max_area = 0
      for key in dictionary:
        if key > max_area and key not in keyset:
          # remove if breaks:
          x, y, w, h = dictionary[key]
          good = True
          for k in dictionary:
            value = dictionary[k]
            if (value[0] > w and value[0] + value[2] < w and value[1] > h and value[1] + value[3] < h):
              good = False
          if good:
            dim = dictionary[key]
            max_area = key
      keyset.add(max_area)
      to_return.append(dim)
    return to_return
    # if max_area:
    #     x, y, w, h = dim
    #     return x - pad, y - pad, w + pad * 2, h + pad * 2

img = cv2.imread("sample_data/testThis.png")

cv2_imshow(img)

img_processed = preprocess(img)
# cv2_imshow(img_processed)
for x,y,w,h in get_region_of_interest(img_processed):
  cv2_imshow(img[y:y + h, x:x + w])

